version: 1.0.{build}
image:
  - macOS
branches:
  only:
    - main
environment:
  my_sonartoken_encrypted:
    secure: pG2bvULhAV4syIfBmSSFvs0ukqiNMasI5+QGC8MwpNoIwNvselOUQmkuiAJ848zb
install:
    - choco install "sonarscanner-msbuild-netcoreapp2.0" -y
before_build:
    - dotnet restore Refactoring.sln
    - dotnet tool install -g dotnet-sonarscanner
    # AppVeyor does not decrypt the secure env vars for PR builds (this prevents someone from submitting PR with malicious build script displaying those variables). So when AppVeyor initiates a Sonar analysis it immediately fails with error "The format of the analysis property sonar.login= is invalid". The only solution is to prevent PR builds initiating Sonar analysis using powershell. See https://medium.com/@stef.heyenrath/how-to-fix-sonarcloud-issue-in-a-github-pr-when-using-appveyor-integration-8909b49406b4    
    - dotnet sonarscanner begin /k:"bharatmane_refactoring" /o:"craftsmanship" /d:"sonar.host.url=https://sonarcloud.io" /d:"sonar.login=$env:my_sonartoken_encrypted"
build:
    project: Refactoring.sln
    verbosity: minimal
after_build:
    - dotnet sonarscanner end /d:"sonar.login=$env:my_sonartoken_encrypted"
notifications:
- provider: Email
  to:
  - bharat.mane@gmail.com
  on_build_success: false
  on_build_failure: false
  on_build_status_changed: true
